apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs-ui
  name: karsajobs-ui
  namespace: karsajobs-ns
spec:
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: karsajobs-ui
  type: NodePort