apiVersion: v1
kind: Service
metadata:
  namespace: karsajobs-ns
  labels:
    app: karsajobs
  name: karsajobssvc
spec:
  ports:
  - port: 80
    nodePort: 30002
  selector:
    app: karsajobs
  type: NodePort